"""
Django settings for chatapp project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import secrets
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the DJANGO_SECRET_KEY environment variable. Without it a throwaway
# key is generated per process, which logs everyone out on each restart - set
# the variable for anything beyond a quick local run.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or secrets.token_urlsafe(50)

def _env_flag(name, default):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: don't run with debug turned on in production!
# Defaults on so a local `runserver` still serves static files; set
# DJANGO_DEBUG=false anywhere it is deployed.
DEBUG = _env_flag('DJANGO_DEBUG', True)

# Permissive while debugging, which suits a webcam on a LAN. With DEBUG off the
# hosts must be named explicitly, so a deployment cannot answer to any Host
# header it is handed.
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [
        host.strip()
        for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
        if host.strip()
    ]


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'records.apps.RecordsConfig',
    'emotion.apps.EmotionConfig',
    'mask.apps.MaskConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'feeds.apps.FeedsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chatapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Absolute, so the templates resolve regardless of working directory.
        'DIRS': [os.path.join(BASE_DIR, 'chatapp', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chatapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }

}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

# This project's sign-in page is /accounts/signin/, not Django's default
# /accounts/login/, so @login_required would otherwise redirect to a 404.
# Both are URL names, resolved by reverse().
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# USE_L10N was deprecated in Django 4.0 and removed in 5.0; localised formatting
# is always on now.

USE_TZ = True

# Django 3.2 onward warns when this is unset. There are no models yet, but the
# default applies to any that get added.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
STATIC_URL = '/static/'

MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL='/media/'


# Recognition tuning
# https://github.com/projjal1/Facial_Recognition_Software
#
# These used to be literals inside identify.py and webcam.py, and the two paths
# disagreed on the confidence cut-off (53 local, 48 remote) for no recorded
# reason. Both values are kept as they were so behaviour is unchanged, but they
# are uncalibrated guesses - deriving them from a false-accept/false-reject
# sweep is a separate piece of work.

# NOTE: these are uncalibrated, and the preprocessing change to fixed-size
# CLAHE crops moved the distance scale they were guessed against. Run
# `manage.py evaluate_recognition` once real people are enrolled and set them
# from the false-accept/false-reject table it prints.
FACE_CONFIDENCE_THRESHOLD_LOCAL = int(os.environ.get('FACE_CONFIDENCE_THRESHOLD_LOCAL', 70))
FACE_CONFIDENCE_THRESHOLD_REMOTE = int(os.environ.get('FACE_CONFIDENCE_THRESHOLD_REMOTE', 70))

# Detection and crop normalisation. Both halves of the pipeline read these, so
# enrolment and recognition cannot drift apart.
FACE_DETECTOR_CONFIDENCE = float(os.environ.get('FACE_DETECTOR_CONFIDENCE', 0.5))
FACE_MIN_SIZE = int(os.environ.get('FACE_MIN_SIZE', 80))
FACE_CROP_SIZE = int(os.environ.get('FACE_CROP_SIZE', 128))
FACE_BLUR_THRESHOLD = float(os.environ.get('FACE_BLUR_THRESHOLD', 40))

# Associating detections across frames, so votes accumulate per person rather
# than in one counter shared by everyone in view.
FACE_TRACK_MAX_DISTANCE = int(os.environ.get('FACE_TRACK_MAX_DISTANCE', 120))
FACE_TRACK_MAX_MISSES = int(os.environ.get('FACE_TRACK_MAX_MISSES', 15))

# Consecutive confident frames before an entry is logged, and consecutive
# failures before an alert is sent.
FACE_FRAMES_TO_LOG = int(os.environ.get('FACE_FRAMES_TO_LOG', 60))
FACE_FRAMES_TO_ALERT = int(os.environ.get('FACE_FRAMES_TO_ALERT', 150))

# Images captured per enrolment run.
FACE_ENROLMENT_FRAMES = int(os.environ.get('FACE_ENROLMENT_FRAMES', 15))

# Usernames that own a face-image folder must match this, because the trainer
# derives each person's numeric label from the folder name. Enforcing it at
# signup turns a silent "never trained" failure into an immediate error.
FACE_USERNAME_PATTERN = r'^s\d+$'

# Enrolled images live one folder per person under here. Keeping them together
# means a single ignore rule covers all biometric data, instead of relying on a
# pattern that has to match folders scattered across the project root.
FACE_IMAGE_ROOT = os.path.join(BASE_DIR, os.environ.get('FACE_IMAGE_ROOT', 'face-files'))

# Optional strict allowlist of camera hosts. Empty means fall back to the
# scheme/loopback/link-local checks in security.validate_camera_url.
CAMERA_URL_ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('CAMERA_URL_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
}

# Several tests deliberately drive failure paths, and the resulting warnings and
# tracebacks are expected output rather than a problem - but interleaved with
# the progress dots they bury the actual result. Raise the level for test runs
# only; DJANGO_LOG_LEVEL still wins if it is set explicitly.
if 'test' in sys.argv and 'DJANGO_LOG_LEVEL' not in os.environ:
    LOGGING['root']['level'] = 'CRITICAL'